version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: dmoj_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${DB_NAME:-dmoj}
      MYSQL_USER: ${DB_USER:-dmoj}
      MYSQL_PASSWORD: ${DB_PASSWORD:-dmoj123}
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root123}
    volumes:
      - mysql_data:/var/lib/mysql
      - ./docker/mysql-init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password --sql_mode="" --innodb-buffer-pool-size=128M --max-connections=50
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M
        reservations:
          cpus: '0.2'
          memory: 200M
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: dmoj_redis
    restart: unless-stopped
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    command: redis-server --maxmemory 64mb --maxmemory-policy allkeys-lru --save 60 1000
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 80M
        reservations:
          cpus: '0.05'
          memory: 32M
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      timeout: 10s
      retries: 5

  web:
    build: .
    container_name: dmoj_web
    restart: unless-stopped
    environment:
      DEBUG: ${DEBUG:-False}
      SECRET_KEY: ${SECRET_KEY:-docker-dev-key}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS:-localhost,127.0.0.1}
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: ${DB_NAME:-dmoj}
      DB_USER: ${DB_USER:-dmoj}
      DB_PASSWORD: ${DB_PASSWORD:-dmoj123}
      DB_HOST: db
      DB_PORT: 3306
      REDIS_URL: redis://redis:6379/0
      SITE_NAME: ${SITE_NAME:-DMOJ}
      SITE_LONG_NAME: ${SITE_LONG_NAME:-DMOJ Modern Online Judge}
      SITE_ADMIN_EMAIL: ${SITE_ADMIN_EMAIL:-admin@example.com}
      SITE_FULL_URL: ${SITE_FULL_URL:-http://localhost:8000}
      DJANGO_SETTINGS_MODULE: dmoj.docker_settings
    volumes:
      - static_files:/app/static
      - media_files:/app/media
      - problem_data:/app/problems
      - ./logs:/app/logs
      - ./static:/app/static_mount
      - ./media:/app/media_mount
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.4'
          memory: 400M
        reservations:
          cpus: '0.2'
          memory: 200M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"] 
      timeout: 10s
      retries: 5
      start_period: 30s
    command: >
      bash -c "
        echo 'Waiting for database...' &&
        while ! mysqladmin ping -h db --silent; do
          echo 'Waiting for database...'
          sleep 2
        done &&
        echo 'Database is ready!' &&
        echo 'Running migrations...' &&
        python manage.py migrate --settings=dmoj.docker_settings &&
        echo 'Building i18n files...' &&
        python manage.py compilejsi18n --settings=dmoj.docker_settings &&
        echo 'Collecting static files...' &&
        python manage.py collectstatic --noinput --settings=dmoj.docker_settings &&
        echo 'Copying static files for nginx...' &&
        mkdir -p /app/static_mount /app/media_mount &&
        cp -r /app/static/* /app/static_mount/ 2>/dev/null || true &&
        cp -r /app/media/* /app/media_mount/ 2>/dev/null || true &&
        echo 'Starting Gunicorn server...' &&
        gunicorn --bind 0.0.0.0:8000 --workers 2 --threads 2 --timeout 60 --max-requests 1000 --max-requests-jitter 100 dmoj.wsgi:application
      "

  celery:
    build: .
    container_name: dmoj_celery
    restart: unless-stopped
    command: celery -A dmoj worker -l info --concurrency=1 --max-tasks-per-child=1000
    environment:
      DEBUG: ${DEBUG:-False}
      SECRET_KEY: ${SECRET_KEY:-docker-dev-key}
      DB_ENGINE: django.db.backends.mysql
      DB_NAME: ${DB_NAME:-dmoj}
      DB_USER: ${DB_USER:-dmoj}
      DB_PASSWORD: ${DB_PASSWORD:-dmoj123}
      DB_HOST: db
      DB_PORT: 3306
      REDIS_URL: redis://redis:6379/0
      DJANGO_SETTINGS_MODULE: dmoj.docker_settings
    volumes:
      - media_files:/app/media
      - problem_data:/app/problems
      - ./logs:/app/logs
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 120M
        reservations:
          cpus: '0.05'
          memory: 64M

volumes:
  mysql_data:
  redis_data:
  static_files:
  media_files:
  problem_data: 